"""Rebuild FIGURES_AND_TABLES.md from the same strings the notebook uses.

The captions live in part5.py and are inserted into the notebook as blockquote cells. This writes
them out as a standalone document for drafting a manuscript from, with the blockquote markers and
HTML entities removed.

It must be re-run whenever a caption or the methods text changes. A hand-maintained copy of the
same prose silently goes stale, and then the manuscript gets drafted from the old wording - which
is exactly what had happened to the previous version of this file.

    python make_figures_doc.py <output.md>
"""
import html
import re
import sys

import part3 as p3
import part4 as p4
import part5 as p5

# (notebook section, the caption string) in the order build_nb.py places them
ORDER = [
    ('A.1', p5.CAP_STRETCH), ('A.1', p5.CAP_WINDOW), ('A.2', p5.CAP_MODELS),
    ('A.3', p5.CAP_TRACER_SUMMARY), ('A.3', p5.CAP_PREVIEW),
    ('A.4', p5.CAP_A4), ('A.5', p5.CAP_POL), ('A.5', p5.CAP_FHTEST),
    ('A.5', p5.CAP_AUDIT), ('A.5', p5.CAP_FHFIG), ('A.6', p5.CAP_KIN),
    ('A.7', p5.CAP_FITCMP), ('A.8', p5.CAP_SWEEP), ('A.8', p5.CAP_SWEEPFIG),
    ('A.9', p5.CAP_BFIELD), ('A.10', p5.CAP_CHAR), ('A.10', p5.CAP_TEXT),
]


def plain(s):
    """Blockquote markers off, HTML entities decoded, bold caption head split into a heading."""
    s = '\n'.join(re.sub(r'^>\s?', '', ln) for ln in s.strip().splitlines())
    return html.unescape(s).strip()


def main(dst):
    out = ['# Figures, tables and methods',
           '## Type II radio burst, 26 March 2025, NenuFAR', '',
           'Captions for every figure and table produced by `plot_nenufar.ipynb`, followed by the',
           'methods description, written for adapting into a manuscript. Section numbers refer to',
           'the notebook; file names refer to the analysis output folder.', '',
           'Generated by `make_figures_doc.py` from the same strings the notebook uses - do not',
           'edit this file by hand, it will be overwritten. Re-run it after changing any caption.',
           '', '---', '']
    for sec, cap in ORDER:
        body = plain(cap)
        head, _, rest = body.partition('\n')
        head = re.sub(r'^\*\*(.+?)\*\*\s*', r'\1 ', head).strip()
        out += [f'### [{sec}] {head}', '', rest.strip(), '', '---', '']
    out += [plain(p4.MD_A11), '', '---', '', plain(p5.MD_A12), '']
    open(dst, 'w').write('\n'.join(out).replace('\n\n\n', '\n\n') + '\n')
    print(f'wrote {dst}: {len(ORDER)} captions + the conventions and methods sections')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'FIGURES_AND_TABLES.md')
